### ISSUE TITLE
Error during installation (craftbukkit 1.6.4)

### ISSUE THREAD

**Issue by Lazerian** [smith61/AdventurePlugin#1]
[SEVERE] Error occurred while enabling AdventurePlugin v1.0.0 (Is it up to date?)
java.lang.NullPointerException
    at me.smith_61.adventure.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:58)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugin(CraftServer.java:282)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.enablePlugins(CraftServer.java:264)
    at net.minecraft.server.v1_6_R3.MinecraftServer.l(MinecraftServer.java:315)
    at net.minecraft.server.v1_6_R3.MinecraftServer.f(MinecraftServer.java:292)
    at net.minecraft.server.v1_6_R3.MinecraftServer.a(MinecraftServer.java:252)
    at net.minecraft.server.v1_6_R3.DedicatedServer.init(DedicatedServer.java:152)
    at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:393)
    at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)

But the plugin works correctly if you add an "AdventurePlugin" folder with a "config.yml" file containing this text:

lobby world: world

adventures:
     NetherAdventure:
         world: world_nether
     EndAdventure:
         world: world_en

Thank you for this plugin, it's great!

**Comment by smith61** [comment]
Fixed in the next version release. Version 2.x.x uses a different loading scheme for adventures than version 1.x.x.
